version: "3.9"

services:
  backend:
    image: ghcr.io/sowjanya-s-mediant-labs/ci-cd-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    restart: always

  frontend:
    image: ghcr.io/sowjanya-s-mediant-labs/ci-cd-frontend:latest
    ports:
      - "5173:5173"
    restart: always
